/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controladores.ControladorInscripcion;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author chris
 */
public class VistaInscripcionn extends javax.swing.JFrame implements IVistaInscripcion {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaInscripcionn.class.getName());

    private final JButton btnAgregar = new JButton("Agregar curso");
    private final JButton btnFinalizar = new JButton("Finalizar inscripción");
    private final JLabel lblTotal = new JLabel("Total: $0.00");
    private final JList<String> lstDisponibles = new JList<>();
    private final JList<String> lstInscritos = new JList<>();

    private ControladorInscripcion controlador;

    /**
     * Creates new form VistaInscripcionn
     */
    public VistaInscripcionn() {
        initComponents();
        setTitle("Inscripción de Clases");
        setSize(500, 400);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLayout(new java.awt.BorderLayout());

        JPanel panelListas = new JPanel(new java.awt.GridLayout(1, 2));
        panelListas.add(new JScrollPane(lstDisponibles));
        panelListas.add(new JScrollPane(lstInscritos));

        JPanel panelBotones = new JPanel();
        panelBotones.add(btnAgregar);
        panelBotones.add(btnFinalizar);
        panelBotones.add(lblTotal);

        add(panelListas, java.awt.BorderLayout.CENTER);
        add(panelBotones, java.awt.BorderLayout.SOUTH);

        btnAgregar.addActionListener(e -> {
            int idx = lstDisponibles.getSelectedIndex();
            if (idx >= 0 && controlador != null) {
                controlador.inscribirCurso(idx); // le pasamos el índice o id
            }
        });
        btnFinalizar.addActionListener(e -> {
            if (controlador != null) {
                controlador.finalizar();
            }
        });
    }

    public void setControlador(ControladorInscripcion c) {
        this.controlador = c;
    }

    // --- estos métodos los llama el controlador ---
    public void setCursosDisponibles(String[] nombres) {
        lstDisponibles.setListData(nombres);
    }

    public void setCursosInscritos(String[] nombres) {
        lstInscritos.setListData(nombres);
    }

    public void setTotal(String total) {
        lblTotal.setText("Total: " + total);
    }

    public void mostrarError(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Error", JOptionPane.ERROR_MESSAGE);
    }

    public void mostrarFicha(String detalle) {
        JOptionPane.showMessageDialog(this, detalle, "Ficha de pago", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaInscripcionn().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
